### ISSUE TITLE
How to set rendering anti-aliasing? And keep it clean and transparent

### ISSUE THREAD

**Issue by thomasbergersen** [yasirkula/UnityRuntimePreviewGenerator#11]
![WX20231020-135310@2x](https://github.com/yasirkula/UnityRuntimePreviewGenerator/assets/3325006/5b45ba3e-2cf3-4eae-ae13-9175803b634f)

**Comment by thomasbergersen** [comment]
<img width="1123" alt="image" src="https://github.com/yasirkula/UnityRuntimePreviewGenerator/assets/3325006/14f5ec9f-a251-43cc-bae9-cdc619ae0d38">
Set to CameraClearFlags.Skybox can have clean transparent channels😄

**Comment by yasirkula** [comment]
Can you try setting RuntimePreviewGenerator.RenderSupersampling to 2? Alternatively, you can use a custom camera with anti-aliasing for rendering: RuntimePreviewGenerator.PreviewRenderCamera

**Comment by thomasbergersen** [comment]
Set RenderSupersampling = 2 antialiasing effect is better, but if can handle clean transparent channel will be better,Thank you.
