### ISSUE TITLE
[Android] RuntimePreviewGenerator generates texture with black background (OpenGLES3, Vulkan)

### ISSUE THREAD

**Issue by AndrewSpalato-FGMNT** [yasirkula/UnityRuntimePreviewGenerator#3]
Unity version: 2019.4.7f1

Imported Runtime Preview Generator package.

Configured runtime preview generator, set background color to Color.clear, also tried new Color(0, 0, 0, 0);

In editor this works, but an Android build shows the resulting texture has a black backgorund fully opaque.

We use the alpha of the preview texture to assist us with raycasting and selecting objects in the scene using Google Cardboard.
I have tried OpenGLES3 and Vulkan graphics API but they show the same result.

Any help would be appreciated.
![Screenshot_20200818-132235_SITU360-test](https://user-images.githubusercontent.com/48661126/90466791-f78e7680-e155-11ea-975e-5bc8c9246066.jpg)

![Screenshot_20200818-132238_SITU360-test](https://user-images.githubusercontent.com/48661126/90466778-f4938600-e155-11ea-8b47-a67e85872e89.jpg)

**Comment by AndrewSpalato-FGMNT** [comment]
Turns out Custom Render Texture was used instead of a Render Texture. Transparency now works as it should.

**Comment by yasirkula** [comment]
Glad the issue is resolved. Can you clarify what you meant by Custom Render Texture?

**Comment by AndrewSpalato-FGMNT** [comment]
I happened to create a Custom Render Texture asset that was used as the Camera's target texture which was also used to generate the preview. Didn't know this existed previously but they are indeed different things. 

More here:
[https://docs.unity3d.com/Manual/class-CustomRenderTexture.html](url)
