### ISSUE TITLE
[Android] Preview generator background opacity ignored when backgroundColor is set. OpenGLES3

### ISSUE THREAD

**Issue by andrewspalato** [yasirkula/UnityRuntimePreviewGenerator#4]
Trying to generate a preview on a simple Unlit/Transparent material on a primitive Quad.

Issue occurs regardless if a render pipeline was set or not.
Tried tweaking player settings with no luck. 

Preview Generator configuration:
RuntimePreviewGenerator.PreviewRenderCamera = null;
RuntimePreviewGenerator.PreviewDirection = Vector3.forward;
RuntimePreviewGenerator.BackgroundColor = new Color(1, 1, 1, 0); // Also occurs using Color.clear and a black background;
RuntimePreviewGenerator.Padding = 0;
RuntimePreviewGenerator.OrthographicMode = true;
RuntimePreviewGenerator.MarkTextureNonReadable = false;

Previews work fine in editor, but Android builds using OpenGLES3 seem to ignore transparency on textures. On Vulkan this works correctly, but the platforms I want to support do not support Vulkan.

Specs:
- Unity version: 2019.4.9f1
- Platform: Android
- Device: Samsung Galaxy S9+, Android 9 (Pie)
- How did you download the plugin: Package Manager: v1.0.0. Using the Asset Store version shows the same result.

Additional info: 
Minimum API Level: 26, Android 8 (Oreo) 
Target API Level: 30

**Comment by andrewspalato** [comment]
I think I was able to fix this by setting Blit Type to Never. Will let you know if I encounter the issue again.

**Comment by yasirkula** [comment]
That's good to hear. I'll also make some research about this issue.

**Comment by yasirkula** [comment]
The closest setup I have is Unity 2019.4.0f1 and Samsung Galaxy S8, Android 9 (Pie). I've tested your script with a Unlit/Transparent quad on a fresh new project using **Blit Type**=Always/Auto and **Graphics APIs**=Only Vulkan/Only OpenGLES3/Only OpenGLES2. I haven't had this issue in neither of these configurations.

I'd recommend you to try the plugin on a fresh new project and if it works, try pinpointing the problematic plugin/Player Settings configuration/post-processing in your original project.
