### ISSUE TITLE
This util doesn't support UI objects

### ISSUE THREAD

**Issue by z3nth10n** [yasirkula/UnityRuntimePreviewGenerator#6]
I created an object with the following hierarchy:

![image](https://user-images.githubusercontent.com/4929135/99148882-a9244180-268a-11eb-9507-36a72c0a7b38.png)

And the following view:

![image](https://user-images.githubusercontent.com/4929135/99148901-cbb65a80-268a-11eb-8253-75febdc3d788.png)

But the following is previewed:

![image](https://user-images.githubusercontent.com/4929135/99148905-dcff6700-268a-11eb-8a95-d1f3536ae6dd.png)

Is there any option to make it work with UI items?

**Comment by yasirkula** [comment]
Unfortunately not. This plugin relies on Renderer.bounds, so I don't think UI will ever be supported (let alone Screen Space - Overlay UI).
