### ISSUE TITLE
Cannot't set background alpha in windows

### ISSUE THREAD

**Issue by futer24** [yasirkula/UnityRuntimePreviewGenerator#7]
RuntimePreviewGenerator.BackgroundColor = Color.clear;  //new Color(1, 1, 1, 0);   //new Color(0.3f, 0.3f, 0.3f, 0f) ;
        tex = RuntimePreviewGenerator.GenerateModelPreview(model.transform ,256,256);
        image.texture = tex; // RawImage

Thanks

**Comment by yasirkula** [comment]
If you double click the Texture of RawImage, you can see in the Inspector whether or not it has an alpha channel. Can you take a screenshot from that Inspector's preview?

**Comment by futer24** [comment]
![image](https://user-images.githubusercontent.com/2451751/99639177-98d3e400-2a47-11eb-91b6-5cc520fbfcd4.png)

**Comment by yasirkula** [comment]
The same code works fine for me. Are you using URP, HDRP or built-in RP? If you are using URP or HDRP, can you also try the plugin on a new project with built-in RP and see if it changes anything?

**Comment by futer24** [comment]
I am using HDRP

**Comment by futer24** [comment]
Yes, I tried with an standard material and the plugin works fine. The problem is with HDRP materials

**Comment by yasirkula** [comment]
Inside your HDRP settings asset, you can try changing Color Buffer Format to R16G16B16A16 since it is the only format that supports alpha channel in RenderTextures but I believe it will have a performance impact :/ There may not be another way to resolve this issue, sadly.

**Comment by futer24** [comment]
> Inside your HDRP settings asset, you can try changing Color Buffer Format to R16G16B16A16 since it is the only format that supports alpha channel in RenderTextures but I believe it will have a performance impact :/ There may not be another way to resolve this issue, sadly.

Yes, it works! thanks

**Comment by marshmatter** [comment]
Sorry to necro, but is there any solution to this same issue with URP?

**Comment by marshmatter** [comment]
Just in case anyone wanders in here, you can absolutely get the transparency working with URP. 

I had to set up a second render pipeline asset to omit all the render features I had in place in order to preserve the alpha channel for the render texture. Then, creating my own camera prefab using the new pipeline asset to pass to the thumbnail generator.  

Thank your for the great little tool!

**Comment by flypart** [comment]
In Unity 2022.3, If you want to generate tansparent icon with URP enabled, please follow this:
https://www.youtube.com/watch?v=Pj1bR0U5Tw4
