### ISSUE TITLE
Render a prefab with Particle System

### ISSUE THREAD

**Issue by Kido-200** [yasirkula/UnityRuntimePreviewGenerator#9]
When render a prefab with Particle System ,the bounds is too larger which make camera too far away ,can't get the true thumbnail.

**Comment by yasirkula** [comment]
I'll probably add a parameter to specify whether or not to include particles in the preview. For now, you can add the following condition to [this for loop](https://github.com/yasirkula/UnityRuntimePreviewGenerator/blob/a037e58807b240697069a1753df7979779cdcf7e/Plugins/RuntimePreviewGenerator/RuntimePreviewGenerator.cs#L329-L341):
```csharp
if( renderersList[i] is ParticleSystemRenderer )
    continue;
```

**Comment by Kido-200** [comment]
Thanks for your replay! But my prefab components all contain a ParticleSystem, it will make "hasBounds" to be "false" and return null directly.
Is there any way to generate a thumbnail of a prefab with ParticleSystem?

**Comment by yasirkula** [comment]
As long as there is a Mesh Renderer or Skinned Mesh Renderer there, hasBounds won't remain false.

**Comment by yasirkula** [comment]
Fixed in https://github.com/yasirkula/UnityRuntimePreviewGenerator/commit/286e800b3b683362973fffde7694231ebdb82d91
